# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db0f2d92c3d01efdea68e08f50d012a7d7bae5df1fe9888cd667b6d49638a6e6378982cfefa83aec52f521eba27210bcb086c9c9d3864904da3dc4621b6a900

test:
  secret_key_base: 3a601bb0c8ec9599719e8cba60493c760e652b523c22599bf214dafba2cc191af8792c7e1c35b669854a1516e86567d157cb9effee4c8e07c0a79686679e134e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
